emu/urls.py
from django.urls import path

from . import views

app_name = 'emu'
urlpatterns = [
    path('', views.HomePage.as_view(), name='home-page'),
    path('item_list/', views.ItemList.as_view(), name='item-list'),
    path('item_view/<int:id>/', views.ItemView.as_view(), name='item-view'),
    path('add_to_cart/', views.AddItemToCart.as_view(), name='add-to-cart'),
    path('checkout/', views.Checkout.as_view(), name='checkout'),
    path('cart_items/', views.CartItems.as_view(), name='cart-items'),
    path('add-coupon/', views.AddCoupon.as_view(), name='add-coupon'),
    path('paypal/', views.PaypalPayment.as_view(), name="paypal"),
    path('stripe/', views.StripePayment.as_view(), name='stripe'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('about/', views.About.as_view(), name='about'),
]

emutech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('emu.urls'), name='emu'),
    path('users/', include('users.urls'), name='users'),
    path('mpesa/', include('mpesa.urls'), name='mpesa'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mpesa/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from .views import STKPush, CallBack, TransactionSuccess, FailedTransaction

app_name = 'mpesa'
urlpatterns = [
    path('stk_push/', csrf_exempt(STKPush.as_view()), name='stk-push'),
    path('call_back/', csrf_exempt(CallBack.as_view()), name='call-back'),
    path('success/', TransactionSuccess.as_view(), name='sucess'),
    path('failed/', FailedTransaction.as_view(), name='failed'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
    )

from . import views

app_name = 'users'
urlpatterns = [
    path('sign up/', views.Register.as_view(), name='register'),
    path('sign in/', views.Login.as_view(), name='login'),
    path('sign out/', views.LogoutUser.as_view(), name='logout'),
    path('password_reset/', PasswordResetView.as_view(template_name='users/password_reset.html', success_url='/users/password_reset_done/',email_template_name='users/password_reset_email.html', subject_template_name='users/password_reset_subject.txt'), name='password-reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password-reset-done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url = '/password_reset_complete/'), name='password_reset_confirm'),
    path('password_reset_complete/',PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    path('change_password/', login_required(views.ChangePassword.as_view(), login_url='users:login'), name='change-password'),
    path('change_password_done/', login_required(views.ChangePasswordDone.as_view()), name='change-password-done'),
]

emu/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

from .models import Contact

PAYMENT_OPTION = (
    ('M', 'Mpesa'),
    ('P', 'PayPal'),
    ('S', 'Stripe'),
)


class CheckoutForm(forms.Form):
    town = forms.CharField(required=False)
    city = forms.CharField(required=False)
    country = CountryField(blank_label='(select country)').formfield(required=False,
                                                                     widget=CountrySelectWidget())
    zip_code = forms.CharField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_OPTION)


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promotion code',
        'aria - label': "Recipient's username",
        'aria - describedby': "basic-addon2"
    }))


class SignUpForm(UserCreationForm):
    email = forms.EmailField(help_text="Enter a valid Email Address")

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class SignInForm(AuthenticationForm):
    username = forms.CharField(max_length=255, help_text="Enter Your Username")
    password = forms.CharField(max_length=255, widget=forms.PasswordInput, help_text="Enter Your Password")

    class Meta:
        model = User
        fields = ('username', 'password')


class ContactForm(forms.ModelForm):
    email_address = forms.EmailField(help_text="Enter Your Email Address")

    # message=forms.CharField(widget=forms.Textarea(attrs={"cols": "58", "rows": "5"}))

    class Meta:
        model = Contact
        # widgets={
        #     "message":forms.Textarea(attrs={"cols": "58", "rows": "5"})
        # }
        fields = ('user', 'email_address', 'message')

emu/views.py
import json
import random

from django import forms as f
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views import View

from .forms import CheckoutForm, CouponForm, SignUpForm, SignInForm, ContactForm
from .models import Item, CartItem, Order, ShippingAddress, GuestCustomer
from .utils import get_coupon, complete_order, update_guest_cart, get_next

guest_order_slug = []
guest_order_customers = []


class HomePage(View):
    def get(self, *args, **kwargs):
        update_guest_cart(self.request)
        context = {}
        return render(self.request, 'emu/home_page.html', context)


class ItemList(View):
    def get(self, *args, **kwargs):
        items = Item.objects.all()
        update_guest_cart(self.request)
        context = {'items': items}
        return render(self.request, 'emu/item_list.html', context)


class ItemView(View):
    def get(self, request, id):
        item = Item.objects.get(id=id)
        update_guest_cart(request)
        context = {'item': item}
        return render(self.request, 'emu/item_view.html', context)


class AddItemToCart(View):
    def get(self, *args, **kwargs):
        return redirect('emu:cart-items')

    def post(self, *args, **kwargs):
        data = json.loads(self.request.body)
        print(data)
        item_id = data['item_id']
        action = data['action']

        item = Item.objects.get(id=item_id)
        order_item, created = CartItem.objects.get_or_create(item=item, user=self.request.user, is_complete=False)
        qs = Order.objects.filter(user=self.request.user, is_complete=False)
        if qs.exists():
            order = qs[0]
            if order.items.filter(item__id=item.id).exists():
                if action == 'add':
                    order_item.quantity += 1
                    messages.info(self.request, f"Successfully increased quantity to - {order_item.quantity}")
                    print("Added")
                elif action == 'remove':
                    order_item.quantity -= 1
                    messages.info(self.request, f"Successfully reduced quantity to - {order_item.quantity}")
                    print("Reduced")
                order_item.save()
                if order_item.quantity <= 0:
                    order_item.delete()
                    messages.info(self.request, "Successfully deleted")
                return JsonResponse("Added successfully", safe=False)
            else:
                order.items.add(order_item)
                messages.info(self.request, "Successfully added")
                return JsonResponse("Added successfully", safe=False)
        else:
            order_date = timezone.now()
            order = Order.objects.create(user=self.request.user)
            order.items.add(order_item)
            messages.info(self.request, f"Successfully added")
            return JsonResponse("Added successfully", safe=False)
            # return redirect('emu:cart-items')


class CartItems(View):
    def get(self, *args, **kwargs):
        try:
            is_guest = False
            if self.request.user.is_authenticated:
                order = Order.objects.get(user=self.request.user, is_complete=False)

            else:
                is_guest = True
                guest = update_guest_cart(self.request)
                cart_items = guest['order']['get_cart_items']
                order_total = guest['order']['get_total']
                items = guest['order']['items']
                for_shipping = guest['order']['for_shipping']
                order = {"get_cart_items": cart_items, 'get_total': order_total, 'items': items,
                         'for_shipping': for_shipping}

            context = {'order': order, 'is_guest': is_guest}

            return render(self.request, 'emu/cart_items.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, 'You do not have an active order.')
            return redirect('/')


class Checkout(View):
    def get(self, *args, **kwargs):
        try:
            is_guest = False
            form = CheckoutForm()
            if self.request.user.is_authenticated:
                order = Order.objects.get(user=self.request.user, is_complete=False)
                context = {'form': form, 'order': order, 'couponform': CouponForm(), 'DISPLAY_COUPON_FORM': True}
                shipping_address_qs = ShippingAddress.objects.filter(
                    user=self.request.user,
                    default=True
                )
                if shipping_address_qs.exists():
                    context.update({'default_address': shipping_address_qs[0]})

                return render(self.request, 'emu/checkout.html', context)
            else:
                is_guest = True
                guest = update_guest_cart(self.request)
                cart_items = guest['order']['get_cart_items']
                order_total = guest['order']['get_total']
                items = guest['order']['items']
                for_shipping = guest['order']['for_shipping']
                order = {"get_cart_items": cart_items, 'get_total': order_total, 'items': items,
                         'for_shipping': for_shipping}
                context = {'form': form, 'order': order, 'couponform': CouponForm(), 'DISPLAY_COUPON_FORM': True,
                           'is_guest': is_guest}
                return render(self.request, 'emu/checkout.html', context)

        except ObjectDoesNotExist:
            messages.info(self.request, 'You do not have an active order.')
            return redirect('emu:checkout')

    def post(self, *args, **kwargs):
        data = json.loads(self.request.body)
        if self.request.user.is_authenticated:

            order = Order.objects.get(user=self.request.user, is_complete=False)
            use_default = data['shippingInfo']['useDefault']
            if use_default:
                address_qs = ShippingAddress.objects.filter(
                    user=self.request.user,
                    default=True)
                if address_qs.exists():
                    shipping_address_1 = address_qs[0]
                    order.shipping_address = shipping_address_1
                    order.save()
            else:
                town = data['shippingInfo']['town']
                city = data['shippingInfo']['city']
                country = data['shippingInfo']['country']
                zip_code = data['shippingInfo']['zipCode']
                shipping_address = ShippingAddress()
                shipping_address.user = self.request.user
                shipping_address.town = town,
                shipping_address.city = city,
                shipping_address.zipe_code = zip_code,
                shipping_address.country = country,
                set_default = data['shippingInfo']['save']
                shipping_address.save()
                order.shipping_address = shipping_address
                order.save()
                if set_default == True:
                    shipping_address.default = True
                    shipping_address.save()
                    order.shipping_address = shipping_address
                    order.save()

            # complete_order(self.request, self.request.user)

        else:
            print(self.request.COOKIES)
            username = data['userInfo']['name']
            email = data['userInfo']['email']
            password = f"PASSWOrdG{random.randint(0, 1000)}"
            print(f"Not logged in {username} {email}")
            customer, created = GuestCustomer.objects.get_or_create(email=email)
            customer.username = username
            customer.password = password
            customer.save()
            user, created = User.objects.get_or_create(username=username, email=email)
            user.password = password
            user.save()

            guest_order_customers.append(username)
            guest_order_customers.append(email)

            guest = update_guest_cart(self.request)
            items = guest['order']['items']
            order = Order.objects.create(user=user)

            for i in items:
                item = Item.objects.get(id=i['item']['id'])
                order_item, created = CartItem.objects.get_or_create(item=item, user=user, is_complete=False)
                order.items.add(order_item)
            use_default = data['shippingInfo']['useDefault']
            if use_default:
                address_qs = ShippingAddress.objects.filter(
                    user=user,
                    default=True)
                if address_qs.exists():
                    shipping_address_1 = address_qs[0]
                    order.shipping_address = shipping_address_1
                    order.save()
            else:
                town = data['shippingInfo']['town']
                city = data['shippingInfo']['city']
                country = data['shippingInfo']['country']
                zip_code = data['shippingInfo']['zipCode']
                shipping_address = ShippingAddress()
                shipping_address.user = user
                shipping_address.town = town,
                shipping_address.city = city,
                shipping_address.zipe_code = zip_code,
                shipping_address.country = country,
                set_default = data['shippingInfo']['save']
                shipping_address.save()
                order.shipping_address = shipping_address
                order.save()
                if set_default:
                    shipping_address.default = True
                    shipping_address.save()
                    order.shipping_address = shipping_address

emu/templates/emu/about.html
{% extends "emu/base.html" %}
{% load static %}
{%block title%}|About{% endblock %}
{% block content %}
<p>About</p>
{% endblock %}

emu/templates/emu/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load cart %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MURSTECH{%block title%}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'emu/css/styles.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/styles.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'mpesa/css/styles.css' %}"/>
    <script src="https://kit.fontawesome.com/4605777c76.js" crossorigin="anonymous"></script>

    <script>
        let user = '{{request.user}}'
        function getToken(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i<cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
        }

        let csrftoken = getToken('csrftoken');
        //console.log(csrftoken)

        function getCookie(name) {
            let cookieArr = document.cookie.split(';');
            for (let i=0; i<cookieArr.length; i++){
              let cookiePair = cookieArr[i].split("=");
              if(name==cookiePair[0].trim()){
                return decodeURIComponent(cookiePair[1]);
              }
            }
            return null;
          }
  
          let cart = JSON.parse(getCookie('cart'));
          if (cart==undefined){
            cart={}
            document.cookie= 'cart='+ JSON.stringify(cart) + ';domian=;path=/'
          }
    </script>
</head>

<body>
<nav class="navbar">
    <div class="nav-container">
        <a id="logo" href="/">MURSTECH</a>
        <input type="checkbox" id="check-box"/>
        <label for="check-box" class="menu-icon">
            <i class="fa-solid fa-bars" id="menu-icon"></i>
            <i class="fa-solid fa-x" id="close-icon"></i>
        </label>
        <ul class="nav-items">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'emu:about' %}" style="--i:0;">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mpesa:stk-push' %}" style="--i:1;">Mpesa</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'emu:item-list' %}" style="--i:2;">Shop</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'emu:contact' %}" style="--i:3;">Contact Us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'emu:add-to-cart' %}" style="--i:4;">Cart <span class="cart-badge">{{request.user|cart_items_count}}</span></a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:change-password' %}" style="--i:5;">Change Password</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}" style="--i:5;">Log Out</a>
            </li>
           
            {%else%}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}" style="--i:6;">Sign In</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}" style="--i:7;">Sign Up</a>
            </li>
            {%endif%}
        </ul>
    </div>
</nav>

<div class="messages" id="messages">
    {% if messages %}
    {% for message in messages %}
    <div class="message text-center alert alert-{{message.tags}} " id="message">
        <p class=""> {{message}}</p>
        <button type="button" class="close" id="close" onClick=closeMessage()>
            <span>&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
</div>

{% block content %}
{% endblock content %}

<script>
    const messageDiv =document.getElementById("message");
    if(messageDiv){
        setTimeout(() => {

            messageDiv.style.display = 'none';
          }, 2000);
        const closeMessage = ()=>{
            messageDiv.style.display="none";
        }
    }

</script>
<script src="{% static 'emu/js/cart.js' %}"></script>
</body>
</html>

emu/templates/emu/checkout.html
{% extends "emu/base.html" %}
{% load static %}
{%block title%}|Checkout{% endblock %}
{% block content %}

<div class="checkout">
    <div class="header">
        <h1>Your Checkout</h1>
    </div>
    <div class="body">
        <form class="form" action="." id="checkout-form">
            {% csrf_token %}
            <div class="user-shipping-info">
                <div class="user-data" id="user-data">
                    <h3>Personal Details</h3>
                    <div class="name-email">
                        <div class="form-fields">
                            <label for="name">Name</label>
                            <input type="text" id="name" name="name" placeholder="Name" autofocus>
                        </div>
                        <div class="form-fields">
                            <label for="email">Email Address</label>
                            <input type="email" id="email" name="email" placeholder="Email address">
                        </div>
                    </div>


                </div>
                <div class="shipping-info" id="shipping-info">
                    <h3>Shipping Address</h3>
                    <div class="town-city" id="towm_city">
                        <div class="form-fields">
                            <label for="town">Town</label>
                            <input type="text" id="town" name="town" placeholder="Town">
                        </div>
                        <div class="form-fields">
                            <label for="city">City</label>
                            <input type="text" id="city" name="city" placeholder="City">
                        </div>
                    </div>
                    <div class="country-zip-code" id="country_zip_code">
                        <div class="country">
                            <label>Country</label>
                            {{form.country}}

                        </div>
                        <div class="zip-code">
                            <label for="zip-code">Zip Code</label>
                            <input type="text" id="zip-code" name="zip_code" placeholder="1234">
                        </div>

                    </div>
                    <div class="save-use">
                        <div class="save" id="save_div">
                            <div class="form-fields">
                                <input type="checkbox" id="save" name="save">
                                <label for="save">Save Address</label>
                            </div>

                        </div>
                        {% if default_address %}

                        <div class="use-default" id="use_default_div">
                            <div class="form-fields">
                                <input type="checkbox" id="use_default" name="use_default">
                                <label for="use_default">Use Default Address - {{default_address.town}}</label>
                            </div>
                        </div>
                        {% endif %}
                    </div>


                </div>
                <div class="payment-options-div" id="payment-options-div">
                    <h3>Select Payment Method</h3>
                    {% for value, name in form.fields.payment_option.choices %}
                    <div class="payment-options">
                        <div class="form-fields">
                            <input type="radio" id="{{name}}" name="payment_option" value="{{value}}">
                            <label for="{{name}}">{{name}}</label>
                        </div>

                    </div>
                    {% endfor %}
                </div>

            </div>
            <div class="proceed-btn" id="proceed-btn">
                <button type="submit" class="btn">Proceed to Pay</button>
            </div>
            <div class="pay-btn" id="pay-btn">
                <button type="submit" class="btn">Continue</button>
            </div>

        </form>

        <div class="cart">
            <div class="header-cart">
                <h3 class="title">Your cart</h3>
                <h3 class="number_of_items">{{order.get_cart_items}}</h3>
            </div>

            <div class="items">
                <div id="authorised">
                    {% for item in order.items.all %}
                    <div class="item">
                        <div class="quantity-name">
                            <h4>{{item.quantity}} x {{item.item.name}}</h4>
                            <small>{{item.item.description}}</small>
                        </div>
                        <div class="price">
                            <h4>${{item.get_price}}</h4>
                        </div>
                    </div>
                    {% endfor%}
                </div>
                {% if is_guest %}
                <div id="not-authorised">
                    {% for item in order.items %}
                    <div class="item">
                        <div class="quantity-name">
                            <h4>{{item.quantity}} x {{item.item.name}}</h4>
                            <small>{{item.item.description}}</small>
                        </div>
                        <div class="price">
                            <h4>${{item.get_price}}</h4>
                        </div>
                    </div>
                    {% endfor%}
                </div>
                {% endif %}


                {% if order.coupon %}
                <div class="">
                    <p class="">Coupon Amount: (${{order.coupon.amount}})</p>
                </div>

                {% endif%}

                <h3 class="total">Total: ${{order.get_total}}</h3>
            </div>
            {% if DISPLAY_COUPON_FORM %}
            <div class="coupon">
                <form class="coupon-form" action="{% url 'emu:add-coupon' %}" method="post">
                    {% csrf_token %}
                    <div class="form-fields">
                        <label for="code"></label>
                        <input type="text" id="code" name="code" placeholder="Promotion code" required>
                    </div>
                    <div class="coupon-submit">
                        <button type="submit">Redeem</button>
                    </div>

                </form>
            </div>
            {% endif %}

        </div>
    </div>

</div>
<script>
    const userData = document.getElementById("user-data");
    const shippingInfo = document.getElementById("shipping-info");
    const paymentDiv = document.getElementById("payment-options-div");
    const proceedBtn = document.getElementById('proceed-btn');
    const payBtn = document.getElementById('pay-btn');
    const checkoutForm = document.getElementById("checkout-form")
    const saveDefault = document.getElementById("save")
    const useDefault = document.getElementById("use_default")
    //console.log(useDefault)

    if (saveDefault){
        saveDefault.addEventListener('change', ()=>{
            if (saveDefault.checked){
                document.getElementById('use_default_div').innerHTML = ''
            }
        })
    }

    if (useDefault){
        useDefault.addEventListener('change', ()=>{
            document.getElementById("save_div").innerHTML = '';
            //shippingInfo.innerHTML = ''
            //document.getElementById("towm_city").innerHTML = '';
            //document.getElementById("country_zip_code").innerHTML = '';
        })
    }

    let shipping = '{{order.for_shipping}}'
    let total = '{{order.get_total}}'
    if(shipping == 'False'){
        //console.log("shipping")
        shippingInfo.innerHTML = '';
    }

    if(user != 'AnonymousUser'){
        userData.innerHTML = ''
    }

    if(user != 'AnonymousUser' && shipping == 'False'){
        //checkoutForm.style.display = 'none';
        shippingInfo.innerHTML = '';
    }

    csrftoken = checkoutForm.getElementsByTagName("input")[0].value;
    proceedBtn.addEventListener('click',()=>{
        paymentDiv.style.display = 'block';
        payBtn.style.display = 'flex';
        shippingInfo.style.display='none';
        userData.style.display = 'none';
        proceedBtn.style.display = 'none';
    })

    payBtn.addEventListener('click', ()=>{
        checkoutData()
    })
    
    checkoutForm.addEventListener('submit',(e)=>{
        e.preventDefault()
        //console.log("Submitting data...")
        //checkoutData()
    })



    const checkoutData = ()=>{
        let userInfo = {
            'name': null,
            'email': null,
            'total': total,
        }

        let shippingInfo={
            'town': null,
            'city': null,
            'zipCode': null,
            'country': null,
            'save': null,
            'useDefault': null,
            
        }
        let paymentOption = checkoutForm.payment_option.value
        if(shipping != 'False'){
            shippingInfo.town = checkoutForm.town.value
            shippingInfo.city = checkoutForm.city.value
            shippingInfo.zipCode = checkoutForm.zip_code.value
            shippingInfo.country = checkoutForm.country.value
            if (checkoutForm.save){
                shippingInfo.save = checkoutForm.save.checked
            }
            
            if(checkoutForm.use_default){
                shippingInfo.useDefault = checkoutForm.use_default.checked
            }
            
        }

        if(user == 'AnonymousUser'){
            userInfo.name = checkoutForm.name.value
            userInfo.email = checkoutForm.email.value
        }

        //console.log(userInfo)
        //console.log(paymentOption)
        if(checkoutForm.use_default){
           // console.log(checkoutForm.use_default)
        }
       
        let url = '/checkout/'
        fetch(url,{
            method: 'POST',
            headers: {
                'Content-type': 'application/json',
                'X-CSRFToken': csrftoken
            },
            body: JSON.stringify({"userInfo": userInfo, "shippingInfo": shippingInfo, "paymentOption": paymentOption})
        })
        .then((response)=>{
            return response.json()
        })
        .then((data)=>{
            //console.log("Success", data)
            //alert("Transaction completed")
            //cart={}
            //document.cookie= 'cart='+ JSON.stringify(cart) + ';domian=;path=/'

            if (paymentOption === 'M'){
                window.location.href = "{% url 'mpesa:stk-push' %}"
            }
            if (paymentOption === 'P'){
                window.location.href = "{% url 'emu:paypal' %}"
            }
            if (paymentOption === 'S'){
                window.location.href = "{% url 'emu:stripe' %}"
            }
            //window.location.href = "{% url 'emu:item-list' %}"
            
        })
    }
</script>

{% endblock content %}

emu/templates/emu/home_page.html
{% extends "emu/base.html" %}
{% load static %}
{% block content %}

<div class='home-page'>
</div>

{% endblock content %}

emu/templates/emu/item_list.html
{% extends "emu/base.html" %}
{% load static %}
{%block title%}|Items{% endblock %}
{% block content %}

<div class='item-list'>
    {% for item in items %}
    {% include 'emu/snippets/item.html' %}
    {% endfor %}
</div>

{% endblock content %}