emu/urls.py
from django.urls import path

from . import views

app_name = 'emu'
urlpatterns = [
    path('', views.HomePage.as_view(), name='home-page'),
    path('item_list/', views.ItemList.as_view(), name='item-list'),
    path('item_view/<int:id>/', views.ItemView.as_view(), name='item-view'),
    path('add_to_cart/', views.AddItemToCart.as_view(), name='add-to-cart'),
    path('checkout/', views.Checkout.as_view(), name='checkout'),
    path('cart_items/', views.CartItems.as_view(), name='cart-items'),
    path('add-coupon/', views.AddCoupon.as_view(), name='add-coupon'),
    path('paypal/', views.PaypalPayment.as_view(), name="paypal"),
    path('stripe/', views.StripePayment.as_view(), name='stripe'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('about/', views.About.as_view(), name='about'),
]

emutech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('emu.urls'), name='emu'),
    path('users/', include('users.urls'), name='users'),
    path('mpesa/', include('mpesa.urls'), name='mpesa'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
    )

from . import views

app_name = 'users'
urlpatterns = [
    path('sign up/', views.Register.as_view(), name='register'),
    path('sign in/', views.Login.as_view(), name='login'),
    path('sign out/', views.LogoutUser.as_view(), name='logout'),
    path('password_reset/', PasswordResetView.as_view(template_name='users/password_reset.html', success_url='/users/password_reset_done/',email_template_name='users/password_reset_email.html', subject_template_name='users/password_reset_subject.txt'), name='password-reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password-reset-done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url = '/password_reset_complete/'), name='password_reset_confirm'),
    path('password_reset_complete/',PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    path('change_password/', login_required(views.ChangePassword.as_view(), login_url='users:login'), name='change-password'),
    path('change_password_done/', login_required(views.ChangePasswordDone.as_view()), name='change-password-done'),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.views import View
from emu.forms import SignUpForm, SignInForm
from emu.utils import get_next


class Register(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            sign_up_form = SignUpForm()
            context = {'sign_up_form': sign_up_form}
            return render(self.request, 'users/register.html', context)
        else:
            logout(self.request)
            sign_up_form = SignUpForm()
            context = {'sign_up_form': sign_up_form}
            return render(self.request, 'users/register.html', context)

    def post(self, *args, **kwargs):
        sign_up_form = SignUpForm(data=self.request.POST)
        if sign_up_form.is_valid():
            new_user = sign_up_form.save()
            login(self.request, new_user)
            return redirect('emu:item-list')
        else:
            context = {'sign_up_form': sign_up_form}
            return render(self.request, 'users/register.html', context)


class Login(View):
    def get(self, *args, **kwargs):
        print(self.request.user)
        get_next.next = self.request.GET.get('next')
        if not self.request.user.is_authenticated:
            sign_in_form = SignInForm()
            context = {'sign_in_form': sign_in_form}
            return render(self.request, 'users/login.html', context)
        else:
            logout(self.request)
            sign_in_form = SignInForm()
            context = {'sign_in_form': sign_in_form}
            messages.success(self.request, "Successfully signed out. Sign In again")
            return render(self.request, 'users/login.html', context)

    def post(self, *args, **kwargs):
        sign_in_form = SignInForm(data=self.request.POST)
        if sign_in_form.is_valid():
            username = sign_in_form.cleaned_data.get('username')
            password = sign_in_form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            print(f"Next: {get_next.next}")
            login(self.request, user)
            if get_next.next:
                return redirect(get_next.next)
            else:
                return redirect('emu:item-list')
        else:
            context = {'sign_in_form': sign_in_form}
            return render(self.request, 'users/login.html', context)


class LogoutUser(View):
    def get(self, *args, **kwargs):
        logout(self.request)
        return redirect('users:login')



class ChangePassword(View):
    def get(self, *args, **kwargs):
        form = PasswordChangeForm(self.request.user)
        context = {'form': form}
        return render(self.request, 'users/change_password.html', context)
    
    def post(self, *args, **kwargs):
        form = PasswordChangeForm(self.request.user, data=self.request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(self.request, user)
            return redirect('users:change-password-done')
        else:
            form = PasswordChangeForm(self.request.user,data=self.request.POST)
            context = {'form': form}
            return render(self.request, 'users/change_password.html', context)

        
class ChangePasswordDone(View):
    def get(self, *args, **kwargs):
        return render(self.request, 'users/change_password_done.html')

users/templates/users/change_password.html
{% extends "emu/base.html" %}
{% load static %}
{%block title%}|Reset Password{% endblock %}
{% block content %}
<div class="center">
	<form method="post" class="login-sign-up-form">
		{% csrf_token %}
	    <h2 class="text-center">Reset Password</h2>
		{% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
        {% endfor %}
        </p>
        {% endfor %}
		<div class="reset-form-buttons">
			<input type="submit" value="Send" class="btn-submit">
			<a href="{%url 'users:login' %}"  class="btn-submit">Cancel</a>
		</div>
	</form>
	</div>
{% endblock %}

users/templates/users/change_password_done.html
{% extends "emu/base.html" %}
{% load static %}
{%block title%}|Change Password Done{% endblock %}
{% block content %}
<div class="login-sign-up-form">
	Password changed successfully.
</div>
{% endblock %}

users/templates/users/login.html
{% extends "emu/base.html" %}
{% load static %}
{%block title%}|Sign In{% endblock %}
{% block content %}

<form action="." method="post" class="login-sign-up-form">
    {% csrf_token %}
    <div class="login-imgcontainer">
        <h1 style="text-align:center;">Sign In</h1>
        <img src="{% static 'emu/images/profile holder.jfif' %}" alt="prfile photo" class="avatar">
    </div>

    <div class="login-container">
        {% for field in sign_in_form %}
        <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in sign_in_form.non_field_errors %}
        <p style="color: red">{{ error }}</p>
        {% endfor %}
        </p>
        {% endfor %}
        <button type="submit">Sign In</button>
        <label>
            <input type="checkbox" checked="checked" name="remember"> Remember me
        </label>
    </div>

    <div class="login-container" style="background-color:#f1f1f1; border-radius: .5rem;">
        <!-- <button type="button" class="cancelbtn">Cancel</button> -->
        <div class="login-links">
            <span class="login-signup"><a href="{% url 'users:register' %}">Sign Up?</a></span>
            <span class="password"><a href="{% url 'users:password-reset' %}">Forgot password?</a></span>
        </div>

    </div>
</form>

{% endblock %}

users/templates/users/logout.html
{% extends "emu/base.html" %}
{% load static %}
{%block title%}|Logout{% endblock %}
{% block content %}
<p>Logout</p>
{% endblock %}

users/templates/users/password_reset.html
{% extends "emu/base.html" %}
{% load static %}
{%block title%}|Reset Password{% endblock %}
{% block content %}
<div class="center">
	<form method="post" class="login-sign-up-form">
		{% csrf_token %}
	    <h2 class="text-center">Reset Password</h2>
		{% for field in form %}
	    		{{ field.label_tag }} 
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small> 
	        	{% endif %}
		{% endfor %}
		<div class="reset-form-buttons">
			<input type="submit" value="Send" class="btn-submit">
			<a href="{%url 'users:login' %}"  class="btn-submit">Cancel</a>
		</div>
	</form>
	</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "emu/base.html" %}
{% load static %}
{%block title%}|Reset Password Done{% endblock %}
{% block content %}

<div class="card center">
	<p>Your password has been changed successfully. Please <a href="{% url 'users:login' %}">Login</a></p>
</div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "emu/base.html" %}
{% load static %}
{%block title%}|Reset Password Done{% endblock %}
{% block content %}

<div class="center">
	<form method="post" class="card">
	  {% csrf_token %}
	  <h2>Password Reset Confirm</h2>
	  
	  {% for field in form %}
	    		{{ field.label_tag }} 
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small> 
	        	{% endif %}
		{% endfor %}
	  
	  
	  <div>
	    <button type="submit" class="btn btn-primary">Reset Password</button>
	  </div>
	</form>
</div>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends "emu/base.html" %}
{% load static %}
{%block title%}|Reset Password Done{% endblock %}
{% block content %}
<div class="login-sign-up-form reset-done" id="reset-done">
	We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

If you don’t receive an email, please make sure you’ve entered the correct Email Address you registered with, and check your spam folder.
</div>
{% endblock %}

users/templates/users/password_reset_email.html
{% autoescape off %}
Dear {{user.username}},

You're receiving this e-mail because you requested a password reset for your account.

Please click the link below to reset your password: 
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

If you did not request a password reset, please ignore this email. Your account remains secure.

For security reasons, this link will expire after 24 hours. If you need further assistance, please contact our support team at 
{{ protocol }}://{{ domain }}{% url 'emu:contact' %}

Kind regards,
{{ site_name }} Support Team.

{% endautoescape %}

users/templates/users/register.html
{% extends "emu/base.html" %}
{% load static %}
{%block title%}|Sign Up{% endblock %}
{% block content %}
<form action="." method="post" class="login-sign-up-form">
    {% csrf_token %}

    {% comment %}
    <div class="signup-imgcontainer">
        <img src="{% static 'emu/images/profile holder.jfif' %}" alt="prfile photo" class="avatar">
    </div>
    {% endcomment %}

    <div class="signup-container">
        <h1 style="text-align:center;">Sign Up</h1>
        {% for field in sign_up_form %}
        <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
        </p>
        {% endfor %}
        <button type="submit">Sign Up</button>
        <div class="login-container" style="background-color:#f1f1f1; border-radius: .5rem;">
            <!-- <button type="button" class="cancelbtn">Cancel</button> -->
            <div class="login-links">
                <span class="login-signup"><a href="{% url 'users:login' %}">Already have an account?</a></span>
                <span class="password"><a href="{% url 'users:login' %}">Sign In?</a></span>
            </div>

        </div>
    </div>
</form>

{% endblock %}